import { CONTENT_TYPES, type Representation } from "@orator/protocol";

/**
 * Cache and conditional-request handling for the public web (SPEC §33).
 *
 * §33.1 puts correctness in revalidation rather than in purging: a short `s-maxage`, an
 * `ETag`, and a great many `If-None-Match` requests that must each be cheap. So the shape
 * of every read route is the same — load the metadata, answer 304 if you can, and only
 * then pay for the body.
 */

/**
 * SPEC §33.2. Not per-route constants: one table, so no page can invent its own policy.
 *
 * Every entry states `max-age` as well as `s-maxage`, and the reason is not symmetry.
 * `s-maxage` addresses shared caches only, so a response carrying it alone gives a *browser*
 * no stated freshness at all — and a cache with no stated freshness is permitted to guess
 * one (RFC 9111 §4.2.2), which in practice means a tenth of the age since `Last-Modified`.
 * For an article published a year ago that is over a month of a reader holding a copy that
 * predates every comment on it.
 *
 * Measured on staging, 2026-08-23: nobody had noticed, because Cloudflare's Browser Cache
 * TTL was rewriting the header on the way out of its cache and imposing four hours of its
 * own. Both are wrong and the fix is one thing — say what we mean.
 */
export const CACHE = {
  article: "public, max-age=60, s-maxage=60, stale-while-revalidate=86400",
  feed: "public, max-age=30, s-maxage=30, stale-while-revalidate=300",
  /**
   * The policies.
   *
   * Five minutes, not the hour this used to say. A policy page costs no D1 read and no R2
   * read — the documents are compiled into the bundle — so the only thing a long TTL buys
   * is a saved Worker invocation, and what it costs is an hour in which the network's terms
   * say something the network no longer says. That is the wrong side of the trade for these
   * three pages in particular.
   */
  policy: "public, max-age=300, s-maxage=300, stale-while-revalidate=86400",
  /** Anything reached with credentials, and anything that failed. */
  private: "private, no-store",
} as const;

/**
 * What Cloudflare's own cache is told (RFC 9213 targeted cache control).
 *
 * A response generated by a Worker does not enter the edge cache on the strength of
 * `Cache-Control` alone — that header addresses shared caches in general, and Cloudflare
 * reads it for origin responses rather than for ones a Worker made up. `Cloudflare-CDN-
 * Cache-Control` is addressed to Cloudflare specifically, and it is what makes §33.1
 * true rather than aspirational: without it every request reaches the Worker, every page
 * costs a D1 query, and the short `s-maxage` protects nothing because nothing is stored.

 */
export const CDN_CACHE = {
  article: "public, max-age=60, stale-while-revalidate=86400",
  feed: "public, max-age=30, stale-while-revalidate=300",
  policy: "public, max-age=300, stale-while-revalidate=86400",
  private: "no-store",
} as const;

export interface Validators {
  etag: string;
  lastModified: string;
}

/**
 * Which build produced this response (SPEC §33.1).
 *
 * Defined by Vite at compile time — see the note in `astro.config.mjs` for why it exists.
 */
export const BUILD_ID: string = __BUILD_ID__;

/**
 * A validator for a representation this build *composes* rather than stores.
 *
 * §33.1 puts correctness in revalidation, and revalidation is only correct when the
 * validator covers the whole entity. An HTML page is stored content plus a template, and a
 * template lives in the deployment: an ETag over the content alone answers "unchanged" to a
 * page that a deployment has just rewritten, and the edge keeps the old one for its whole
 * `stale-while-revalidate` window.
 *
 * So: anything assembled here — a rendered page, a policy with its links rewritten, a JSON
 * envelope — carries the build. An article's `.md` is the author's bytes and nothing else,
 * and does not: rebuilding the site does not change what they wrote.
 */
export const composedEtag = (etag: string): string => `${etag}.${BUILD_ID}`;

/**
 * The ETag, as a weak validator.
 *
 * Weak rather than strong, and deliberately so. The hash identifies the revision's content;
 * the bytes on the wire are that content in whatever encoding was negotiated. Those are
 * semantically equivalent and not octet-identical, which is exactly what "weak" means.
 *
 * Cloudflare settles the question anyway: it rewrites a strong ETag to a weak one whenever
 * it compresses a response, and every browser asks for compression. Declaring strong would
 * mean the header we send is not the header any reader receives — verified on staging,
 * where `curl` sees a strong ETag and `curl --compressed` sees a weak one.
 */
export const quoteEtag = (etag: string): string => `W/"${etag}"`;

/** Compares ignoring weakness and quoting, which is what a weak comparison is. */
const sameEntity = (a: string, b: string): boolean =>
  a.replace(/^W\//, "") === b.replace(/^W\//, "");

/**
 * Answers a conditional request, or returns null to mean "carry on and render".
 *
 * Called before the body is read, which is the entire point: §33.3 promises revalidation
 * costs one indexed D1 query, and it only does if the R2 read happens after this.
 */
export function notModified(
  request: Request,
  validators: Validators,
  /**
   * Which row of the CACHE table this 304 restates.
   *
   * A 304 carries the freshness the cache should now apply, so answering a policy page's
   * revalidation with an article's sixty seconds would quietly shorten it. Defaults to the
   * article's, which is what every caller but the policies wants.
   */
  policy: keyof typeof CACHE = "article",
): Response | null {
  const tag = quoteEtag(validators.etag);
  const ifNoneMatch = request.headers.get("if-none-match");
  if (ifNoneMatch === null) return null;

  // A cache may send several at once, and an intermediary may have weakened ours further.
  const matches = ifNoneMatch
    .split(",")
    .map((value) => value.trim())
    .some((value) => value === "*" || sameEntity(value, tag));
  if (!matches) return null;

  return new Response(null, {
    status: 304,
    headers: {
      etag: tag,
      "cache-control": CACHE[policy],
      "cloudflare-cdn-cache-control": CDN_CACHE[policy],
      "last-modified": new Date(validators.lastModified).toUTCString(),
    },
  });
}

export function cacheHeaders(
  headers: Headers,
  policy: string,
  cdnPolicy: string,
  validators?: Validators,
): void {
  headers.set("cache-control", policy);
  headers.set("cloudflare-cdn-cache-control", cdnPolicy);
  if (validators === undefined) return;
  headers.set("etag", quoteEtag(validators.etag));
  headers.set("last-modified", new Date(validators.lastModified).toUTCString());
}

/**
 * A machine-readable representation of an article (§48).
 *
 * `X-Robots-Tag: noindex` is not an afterthought. The same article at three URLs is exactly
 * the duplicate-content pattern §50.2 warns about; the HTML page is the one that should be
 * indexed, and the `Link: rel=canonical` header says which that is for anything that reads
 * headers rather than markup.
 */
export function representationResponse(
  body: string,
  representation: Exclude<Representation, "html">,
  options: {
    validators: Validators;
    canonicalUrl: string;
    /** Which row of the CACHE table applies. An article's, unless said otherwise. */
    policy?: keyof typeof CACHE;
  },
): Response {
  const headers = new Headers({
    "content-type": CONTENT_TYPES[representation],
    "x-robots-tag": "noindex",
    link: `<${options.canonicalUrl}>; rel="canonical"`,
  });
  const row = options.policy ?? "article";
  cacheHeaders(headers, CACHE[row], CDN_CACHE[row], options.validators);
  return new Response(body, { headers });
}

/** SPEC §14.2 — a permanent redirect, because the canonical URL of an article is stable. */
export const permanentRedirect = (to: string): Response =>
  new Response(null, {
    status: 301,
    headers: {
      location: to,
      "cache-control": CACHE.article,
      "cloudflare-cdn-cache-control": CDN_CACHE.article,
    },
  });

/**
 * SPEC §33.5 — `Accept` is the secondary mechanism, and it redirects.
 *
 * 302 rather than 301: the redirect depends on a request header, and a browser that cached
 * it permanently would be stuck sending a reader to the markdown source of every article.
 */
export const negotiatedRedirect = (to: string): Response =>
  new Response(null, {
    status: 302,
    headers: {
      location: to,
      "cache-control": CACHE.private,
      "cloudflare-cdn-cache-control": CDN_CACHE.private,
    },
  });
