import { CONTENT_TYPES, type Representation } from "@orator/protocol";

/**
 * Cache and conditional-request handling for the public web (SPEC §33).
 *
 * §33.1 puts correctness in revalidation rather than in purging: a short `s-maxage`, an
 * `ETag`, and a great many `If-None-Match` requests that must each be cheap. So the shape
 * of every read route is the same — load the metadata, answer 304 if you can, and only
 * then pay for the body.
 */

/** SPEC §33.2. Not per-route constants: one table, so no page can invent its own policy. */
export const CACHE = {
  article: "public, s-maxage=60, stale-while-revalidate=86400",
  feed: "public, s-maxage=30, stale-while-revalidate=300",
  /** Anything reached with credentials, and anything that failed. */
  private: "private, no-store",
} as const;

/**
 * What Cloudflare's own cache is told (RFC 9213 targeted cache control).
 *
 * A response generated by a Worker does not enter the edge cache on the strength of
 * `Cache-Control` alone — that header addresses shared caches in general, and Cloudflare
 * reads it for origin responses rather than for ones a Worker made up. `Cloudflare-CDN-
 * Cache-Control` is addressed to Cloudflare specifically, and it is what makes §33.1
 * true rather than aspirational: without it every request reaches the Worker, every page
 * costs a D1 query, and the short `s-maxage` protects nothing because nothing is stored.

 */
export const CDN_CACHE = {
  article: "public, max-age=60, stale-while-revalidate=86400",
  feed: "public, max-age=30, stale-while-revalidate=300",
  private: "no-store",
} as const;

export interface Validators {
  etag: string;
  lastModified: string;
}

/**
 * The ETag, as a weak validator.
 *
 * Weak rather than strong, and deliberately so. The hash identifies the revision's content;
 * the bytes on the wire are that content in whatever encoding was negotiated. Those are
 * semantically equivalent and not octet-identical, which is exactly what "weak" means.
 *
 * Cloudflare settles the question anyway: it rewrites a strong ETag to a weak one whenever
 * it compresses a response, and every browser asks for compression. Declaring strong would
 * mean the header we send is not the header any reader receives — verified on staging,
 * where `curl` sees a strong ETag and `curl --compressed` sees a weak one.
 */
export const quoteEtag = (etag: string): string => `W/"${etag}"`;

/** Compares ignoring weakness and quoting, which is what a weak comparison is. */
const sameEntity = (a: string, b: string): boolean =>
  a.replace(/^W\//, "") === b.replace(/^W\//, "");

/**
 * Answers a conditional request, or returns null to mean "carry on and render".
 *
 * Called before the body is read, which is the entire point: §33.3 promises revalidation
 * costs one indexed D1 query, and it only does if the R2 read happens after this.
 */
export function notModified(request: Request, validators: Validators): Response | null {
  const tag = quoteEtag(validators.etag);
  const ifNoneMatch = request.headers.get("if-none-match");
  if (ifNoneMatch === null) return null;

  // A cache may send several at once, and an intermediary may have weakened ours further.
  const matches = ifNoneMatch
    .split(",")
    .map((value) => value.trim())
    .some((value) => value === "*" || sameEntity(value, tag));
  if (!matches) return null;

  return new Response(null, {
    status: 304,
    headers: {
      etag: tag,
      "cache-control": CACHE.article,
      "cloudflare-cdn-cache-control": CDN_CACHE.article,
      "last-modified": new Date(validators.lastModified).toUTCString(),
    },
  });
}

export function cacheHeaders(
  headers: Headers,
  policy: string,
  cdnPolicy: string,
  validators?: Validators,
): void {
  headers.set("cache-control", policy);
  headers.set("cloudflare-cdn-cache-control", cdnPolicy);
  if (validators === undefined) return;
  headers.set("etag", quoteEtag(validators.etag));
  headers.set("last-modified", new Date(validators.lastModified).toUTCString());
}

/**
 * A machine-readable representation of an article (§48).
 *
 * `X-Robots-Tag: noindex` is not an afterthought. The same article at three URLs is exactly
 * the duplicate-content pattern §50.2 warns about; the HTML page is the one that should be
 * indexed, and the `Link: rel=canonical` header says which that is for anything that reads
 * headers rather than markup.
 */
export function representationResponse(
  body: string,
  representation: Exclude<Representation, "html">,
  options: { validators: Validators; canonicalUrl: string },
): Response {
  const headers = new Headers({
    "content-type": CONTENT_TYPES[representation],
    "x-robots-tag": "noindex",
    link: `<${options.canonicalUrl}>; rel="canonical"`,
  });
  cacheHeaders(headers, CACHE.article, CDN_CACHE.article, options.validators);
  return new Response(body, { headers });
}

/** SPEC §14.2 — a permanent redirect, because the canonical URL of an article is stable. */
export const permanentRedirect = (to: string): Response =>
  new Response(null, {
    status: 301,
    headers: {
      location: to,
      "cache-control": CACHE.article,
      "cloudflare-cdn-cache-control": CDN_CACHE.article,
    },
  });

/**
 * SPEC §33.5 — `Accept` is the secondary mechanism, and it redirects.
 *
 * 302 rather than 301: the redirect depends on a request header, and a browser that cached
 * it permanently would be stuck sending a reader to the markdown source of every article.
 */
export const negotiatedRedirect = (to: string): Response =>
  new Response(null, {
    status: 302,
    headers: {
      location: to,
      "cache-control": CACHE.private,
      "cloudflare-cdn-cache-control": CDN_CACHE.private,
    },
  });
